version: '3'
services:
  service1:
    build: ./service-1
    container_name: service1
    ports:
      - "8081:8081"
  service2:
    build: ./service-2
    container_name: service2
    ports:
      - "8082:8082"
  nginx:
    build: ./nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2

